#!/usr/bin/sh

#Custom verify script to emulate mvn verify. similar to pre-commit hook

PYTEST_FAIL_FLAG=0
RUFF_LINT_FLAG=0
BANDIT_FAIL_FLAG=0

uv run ruff check
if [ $? -ne 0 ]
then
    RUFF_LINT_FLAG=1
fi

#Coverage juckt hier nicht, geht nur um tests erfüllt oder nicht für local build
uv run pytest -n auto
if [ $? -ne 0 ]
then
    PYTEST_FAIL_FLAG=1
fi

uv run bandit togepy -r
if [ $? -ne 0 ]
then
    BANDIT_FAIL_FLAG=1
fi

echo ""
echo "--------------- UV Verify: Conditional Building ---------------"
echo "[1/4] Running ruff, linting..."
if [ $RUFF_LINT_FLAG -eq 1 ]
then
	echo "✗ Lint failed"
else
	echo "✓ Lint passed"
fi
echo ""
echo "[2/4] Running tests..."
if [ $PYTEST_FAIL_FLAG -eq 1 ]
then
	echo "✗ Tests failed"
else
	echo "✓ Tests passed"
fi
echo ""
echo "[3/4] Running security checks..."
if [ $BANDIT_FAIL_FLAG -eq 1 ]
then
	echo "✗ Tests failed"
else
	echo "✓ Tests passed"
fi

echo ""
echo "[4/4] Building package..."
if [ $PYTEST_FAIL_FLAG -eq 1 ] || [ $RUFF_LINT_FLAG -eq 1 ] || [ $BANDIT_FAIL_FLAG -eq 1 ]
then
	echo "✗ Building failed"
	echo ""
	echo ""
	echo "--> Verify failed! Check above to see why"
	echo "---------------------------------------------------------------"
	exit 1
else
	echo "all conditions met, commencing build..."
	echo ""
	uv build
	if [ $? -ne 0 ]
	then
		echo "✗ Building failed"
		echo ""
		echo ""
		echo "--> Verify (Building) failed! Check above to see why"	#something in build went wrong despite lint+test being successful, thats why there is (Building) to identify
		echo "----------------------------------------"
		exit 1
	else
		echo ""
		echo "✓ Build successful"
		echo ""
		echo ""
		echo "--> Verify successful! Artifact in ./dist/."
		echo "----------------------------------------"
	fi

fi
exit 0
